### ISSUE TITLE
Why no 2.3 in master?

### ISSUE THREAD

**Issue by DamienCassou** [YunoHost-Apps/wallabag2_ynh#45]
Hi,

I've seen that you reverted the change merging 2.3 in master? Why did you do that? Isn't the 2.3 branch ready?

Best

**Comment by JimboJoe** [comment]
Hi, the 2.3 branch is not ready yet (due to [this](https://github.com/wallabag/wallabag/issues/3485) upstream bug that makes sub-directory installations fail).

Moreover, our new official apps policy implies an open testing phase before releasing in master (see dedicated forum post [here](https://forum.yunohost.org/t/testing-branches-for-apps/3470)). But you're free to help at any stage 😉

**Comment by lapineige** [comment]
>  But you're free to help at any stage 😉

And that means that when 2.3 branch (or any other version branch) is ready for merging, meanwhile you can use it on your side - at your own risks - to test it :)

> I've seen that you reverted the change merging 2.3 in master? 

As indicated in the commit description, it was a mistake, I forgot the change the branch before doing my change.
And it was not an update, just changing the README.md, nothing else.

If you want to test (not for production !) 2.3, you can help us :)
Or you will have to wait a few days to ensure that we won't break your wallabag during the update, to have more time to test it and check if it doesn't create new issues.

**Comment by raf64flo** [comment]
Hi. As far as I can see, the shipped version is currently 2.3.2 which is the latest to this day (https://github.com/wallabag/wallabag/tree/master).

May we close this issue?
