### ISSUE TITLE
Confirmation email

### ISSUE THREAD

**Issue by deljones** [YunoHost-Apps/wallabag2_ynh#91]
Hi 

I have just installed Wallabag into my YNH server.

It kind of works in that I can save links for reading later but I can't see them. If I click on any saved item I get told that I need to respond to an email confirmation. I am the only user. I don't mind getting my hands dirty on the command line but until I can read my article later then it's kind of useless. 

I like Wallabag a lot and use it but can't seem to get it to work fully on YNH. 

I know that I might have missed something really obvious!!

Best wishes

Dj

**Comment by lapineige** [comment]
I don't remember that step (maybe that's something new, I don't think I had to confirm my email 🤔), but it's probably your yunohost user email (you can see it on yunohost main page, under your pseudo). If you don't redirect them to another account, they are accessible locally, using for instance the Roundcube app. You might need to install it in order to check that email.

**Comment by deljones** [comment]
@lapineige thanks for reading and replying.

Yes the problem is there is no where to put your email address in. I had roundcube already installed before wallabag but no email came.... Hmmmm....

Dj

**Comment by deljones** [comment]
Fixed...! It was a new install so there was no real useful stuff in there yet so I just uninstalled and reinstalled it... All good.

Whew!

Dj

**Comment by lapineige** [comment]
Did it ask for an email address ?
